# apply file: 
#   kubectl apply -f mongo.yaml
# show status:
#   kubectl get all
#   kubectl get pod
# additional information:
#   kubectl get pod -o wide

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
          - containerPort: 27017
        env:
        - name: MONGO_INIT_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username
        - name: MONGO_INIT_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
---
# kubectl get service
# kubectl describe service mongodb-deployment
apiVersion: v1
kind: Service
metadata:
  name: mongodb-deployment
spec:
  selector:
    app: mongodb
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
